<div style="float:left">
    <h1 style="width:450px">Practical 4: Object-Oriented Programming</h1>
    <h2 style="width:450px">Getting to grips with Functions &amp; Packages</h2>
</div>
<div style="float:right"><img width="100" src="https://github.com/jreades/i2p/raw/master/img/casa_logo.jpg" /></div>

<div class="alert alert-block alert-warning">
    <b>&#9888; Important</b>: This is a very long practical and it's <em>not</em> expected that you will get through it in the alloted time. The priorities here should be tasks 1--4. Task 5 is something you will probably want to revist before the start of group work (because packges of functions are useful when multiple people are working on the same code). Task 6 will help you to understand <i>how</i> to build your own classes in greater detail, but it is enough to understand that classes exist in hierarchies (as covered in the live session).</div>

## Task 1 (Revisited). Why 'Obvious' is Not Always 'Right'

Practical 3 is hard, so I want to provide _another_ chance for the concepts to bed in before we use them in an *object-oriented way through Pandas*. Yes, Week 5 will show how we combine concepts covered over the preceding two weeks in *practice* to do data science. 

So remember the finding from last week: if we don't really care about column order, then a dictionary of lists would be a nice way to handle data. And why should we care about column order? With our CSV file we saw what a pain it was to fix things when even a tiny thing like the layout of the columns changed. But if, instead, we could just reference the 'Description' column in the data set then it doesn't matter where that column actually is *and* we would know that all the descriptions would be *text*, while all the populations or prices would be *numbers*. Why is that? 

### Task 1.1 The Way That Doesn't Work

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low (this time around).</div>

Here are four rows of 'data' for city sizes organised by _row_ as a list-of-lists. Try printing out *just* the cities contained in the data:

In [6]:
# 在week3 基础上的练习😊

myData = [
    ['id', 'Name', 'Rank', 'Longitude', 'Latitude', 'Population'], 
    ['1', 'Greater London', '1', '-18162.92767', '6711153.709', '9787426'], 
    ['2', 'Greater Manchester', '2', '-251761.802', '7073067.458', '2553379'], 
    ['3', 'West Midlands', '3', '-210635.2396', '6878950.083', '2440986']
]

#### 1.1.1 Print a List of Cities

Print out a list of every city in the data set:

In [7]:
col    = myData[0].index('Name')
cities = []

# for i in range(1,4):cities.append...

for i in range(1, len(myData)):
    cities.append(myData[i][col])
    
print("The cities in the data set are: " + ", ".join(cities))

The cities in the data set are: Greater London, Greater Manchester, West Midlands


#### 1.1.2 Is Edinburgh in the List?

Now write code to find out if `Edinburgh` is included in the list of data:

In [8]:
found = False
for i in range(1, len(myData)):
    if myData[i][col] == 'Edinburgh':
        print("Found Edinburgh in the data set!")
        found = True
        break

if found == False:
    print("Didn't find Edinburgh in the data set.")

Didn't find Edinburgh in the data set.


### Task 1.2 The Way That Does Work

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low (this time around).</div>

Compare that code to how it works for a dictionary-of-lists organised by _column_. Now try printing out the cities in the data:

In [9]:
myData = {
    'id'         : [0, 1, 2, 3, 4, 5],
    'Name'       : ['Greater London', 'Greater Manchester', 'Birmingham','Edinburgh','Inverness','Lerwick'],
    'Rank'       : [1, 2, 3, 4, 5, 6],
    'Longitude'  : [-0.128, -2.245, -1.903, -3.189, -4.223, -1.145],
    'Latitude'   : [51.507, 53.479, 52.480, 55.953, 57.478, 60.155],
    'Population' : [9787426, 2705000, 1141816, 901455, 70000, 6958],
}

#### 1.2.1 Print a List of Cities

Print out a list of every city in the data set:

In [10]:
# 继续以练习方式证明week3 提到的dictionaries 好处 👇

# What cities are in the data set?
print(", ".join(myData['Name']))

Greater London, Greater Manchester, Birmingham, Edinburgh, Inverness, Lerwick


#### 1.1.2 Is Edinburgh in the List?

Now write code to find out if `Edinburgh` is included in the list of data:

In [11]:
if 'Edinburgh' in myData['Name']:
    print("Found Edinburgh in the data set!")
else:
    print("Didn't find Edinburgh in the data set.")

Found Edinburgh in the data set!


See how even basic questions like "Is Edinburgh in our list of data?" are suddenly easy to answer? We no longer need to loop over the entire data set in order to find one data point. In addition, we know that everything in the 'Name' column will be a string, and that everything in the 'Longitude' column is a float, while the 'Population' column contains integers. So that's made life easier already. But let's test this out and see how it works.

### Task 1.3 Appending a Column

To give you a sense of how scaleable this approach to data is let's add a new column where the population is standardised to a z-score. Remember that the format for the z-score is: 

$$
z = \frac{x - \bar{x}}{\mu}
$$

#### 1.3.1 Calculate Mean & Std Dev

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low-ish.</div>

Let's start by calculating the sample mean and standard deviation (use Google: `Python numpy mean...`):

In [12]:
# 使用numpy计算数据 🐱
# mean平均值 std标准值
# {std:,.2f}  2f保留小数点后2位

import numpy as np
# Use numpy functions to calculate mean and standard deviation
mean = np.mean(myData['Population'])
std  = np.std(myData['Population'])
print(f"City distribution has a mean {mean:,.0f} and standard deviation of {std:,.2f}.")

City distribution has a mean 2,435,442 and standard deviation of 3,406,947.93.


`numpy` gives us a way to calculate the mean and standard deviation _quickly_ and without having to reinvent the wheel. The other potentially new thing here is `{std:,.2f}`. This is about [string formatting](https://www.w3schools.com/python/ref_string_format.asp) and the main thing to recognise is that this means 'format this float with commas separating the thousands/millions and 2 digits to the right'. The link I've provided uses the slightly older approach of `<str>.format()` but the formatting approach is the same.

#### 1.3.2 For Loops Without For Loops

<div class="alert alert-block alert-warning"><b>Difficulty level</b>: Medium.</div>

Now we're going to see something called a **List Comprehension**.

In Python you will see code like this a lot: `[x for x in list]`. This syntax is known as a 'list comprehension' and is basically a `for` loop on one line with the output being assigned to a list. So we can apply an operation (converting to a string, subtracting a value, etc.) to every item in a list without writing out a full for loop.

Here's a quick example just to show you what's going on:

In [13]:
# for循环 🌙
# [x for x in list]  
# 第二个 x是设定的，存在某数据列表中，但不指定是哪个数据
# 第一个 x是设定x的计算/操作
# 使用for循环：列表中的每一项应用第一个x 的计算/操作


demo = range(0,10) # <- a *range* of numbers between 0 and 9 (stop at 10)
print([x**2 for x in demo]) # square every element of demo

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Now let's apply this to our problem. We calculated the the mean and standard deviation above, so now we want to apply the z-score formula to every element of the Population list... 

In [15]:
# 对此题解读
# x在数据'Population' 列表中，但不指定是哪个数据
# （x - mean)/std = x减去mean除standard
# 'Population'列表每一数据都这么做

rs = [(x - mean)/std for x in myData['Population']] # rs == result set
print([f"{x:.3f}" for x in rs])

['2.158', '0.079', '-0.380', '-0.450', '-0.694', '-0.713']


#### 1.3.3 Appending

<div class="alert alert-block alert-success"><b>Difficulty level</b>: trivial</div>

And now let's add it to the data set:

In [17]:
# 上一步计算的rs加入到原数据myData里
# 需要 定义myData的'Std.Population' 是rs

myData['Std. Population'] = rs
print(myData['Std. Population'])
print(myData)

[2.1579383252868527, 0.0791199354729932, -0.3797024575689938, -0.45025269939207097, -0.6942995760276591, -0.7128035277711219]
{'id': [0, 1, 2, 3, 4, 5], 'Name': ['Greater London', 'Greater Manchester', 'Birmingham', 'Edinburgh', 'Inverness', 'Lerwick'], 'Rank': [1, 2, 3, 4, 5, 6], 'Longitude': [-0.128, -2.245, -1.903, -3.189, -4.223, -1.145], 'Latitude': [51.507, 53.479, 52.48, 55.953, 57.478, 60.155], 'Population': [9787426, 2705000, 1141816, 901455, 70000, 6958], 'Std. Population': [2.1579383252868527, 0.0791199354729932, -0.3797024575689938, -0.45025269939207097, -0.6942995760276591, -0.7128035277711219]}


And just to show how everything is in a single data structure:

In [18]:
# 展示数据结构

for c in myData['Name']:
    idx = myData['Name'].index(c)
    print(f"{c} has a population of {myData['Population'][idx]:,} and standardised score of {myData['Std. Population'][idx]:.3f}")

Greater London has a population of 9,787,426 and standardised score of 2.158
Greater Manchester has a population of 2,705,000 and standardised score of 0.079
Birmingham has a population of 1,141,816 and standardised score of -0.380
Edinburgh has a population of 901,455 and standardised score of -0.450
Inverness has a population of 70,000 and standardised score of -0.694
Lerwick has a population of 6,958 and standardised score of -0.713


## Task 2. 'Functionalising'

Let's start trying to pull what we've learned over the past two weeks together by creating a a set of functions that will help us to:

1. Download a file from a URL (checking if it has already _been_ downloaded to save bandwidth).
2. Parse it as a CSV file and...
3. Convert it to a Dictionary-of-Lists
4. Perform some simple calculations using the resulting data.

To be honest, there's not going to be much about writing our _own_ objects here, but we will be making use of them and, conceptually, an understanding of objects and classes is going to be super-useful for understanding what we're doing in the remainder of the term!

### Task 2.1: Downloading from a URL

Let's focus on the first part *first* because that's the precondition for everything else. If we can get the 'download a file from a URL' working then the rest will gradually fall into place through *iterative* improvments!

#### 2.1.1 Finding an Existing Answer

First, let's be sensibly lazy--we've already written code to read a file from the Internet and turn it into a list of lists. So I've copy+pasted that into the code block below since we're going to start from this point; however, just to help you check your own understanding, I've removed a few bits and replacement with `??`. Sorry. 😈

In [19]:
# 从URL下载存于网站的csv数据 🦁
# 启用urlopen功能

from urllib.request import urlopen
import csv

# url读取数据
url = "https://raw.githubusercontent.com/jreades/fsds/master/data/src/Wikipedia-Cities-simple.csv"

# 储存数据
urlData = [] 

# 将 url读入名为'response'的变量
# 从 response中读取，解码，这样就能得到真正的文本
response = urlopen(url) 
csvfile  = csv.reader(response.read().decode('utf-8').splitlines()) 

# 展示读取的
for row in csvfile:
    urlData.append(row)

print("urlData has " + str(len(urlData)) + " rows and " + str(len(urlData[0])) + " columns.")
print(urlData[-1]) # Check it worked!

urlData has 11 rows and 4 columns.
['Bangor', '18808', '53.228', '-4.128']


You should get `urlData has 11 rows and 4 columns.` and a row that looks like this: `['Bangor', '18808', '53.228', '-4.128']`.

#### 2.1.2 Getting Organised

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low</div>

Let's take the code above and modify it so that it is:

1. A function that takes two arguments: a URL; and a destination filename.
2. Implemented as a function that checks if a file exists already before downloading it again.

You will find that the `os` module helps here because of the `path` function. And you will [need to Google](https://lmgtfy.app/?q=check+if+file+exists+python) how to test if a file exists. I would normally select a StackOverflow link in the results list over anything else because there will normally be an _explanation_ included of why a particular answer is a 'good one'. I also look at which answers got the most votes (not always the same as the one that was the 'accepted answer'). In this particular case, I also found [this answer](https://careerkarma.com/blog/python-check-if-file-exists/) useful.

I would start by setting my inputs:

In [20]:
# os包里有path函数
# os.path.join（） 智能地连接一个或多个路径组件

# out 就代表着 'data'文件夹下'Wikipedia-Cities.csv'这个文件


import os
url = "https://raw.githubusercontent.com/jreades/fsds/master/data/src/Wikipedia-Cities-simple.csv"
out = os.path.join('data','Wikipedia-Cities.csv') # Print `out` if you aren't sure what this has done!

print(out)

data/Wikipedia-Cities.csv


#### 2.1.3 Sketching the Function

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low</div>

Then I would sketch out how my function will work using comments. And the simplest thing to start with is checking whether the file has already been downloaded:

In [16]:
# 检查文件是否下载 😀

# # 启用urlopen功能
from urllib.request import urlopen


# get_url(src,dest)  src和dest 是get_url里的两个参数
# get_url(url, out)  url和out 也是get_url里的两个参数
# src 对应 url    dest 对应 out
def get_url(src, dest):
    
    # os.path.isfile()：判断某一对象是否为文件
    # os.path.isdir()：判断某一对象是否为目录
   
    if os.path.isfile(dest):
        print(f"{dest} found!")
    else:
        print(f"{dest} *not* found!")
        
get_url(url, out)

data/Wikipedia-Cities.csv found!


#### 2.1.4 Fleshing Out the Function 

<div class="alert alert-block alert-warning"><b>Difficulty level</b>: Medium, if you really explore what's going on in the function rather than just running it and moving on.</div>

I would then flesh out the code so that it downloads the file if it isn't found and then, either way, returns the *local* file path for our CSV reader to extract:

In [22]:
# 检查文件是否下载 😀
# 在没有找到文件时下载文件

def get_url(src, dest):
    
    # 检查 dest文件是否存在（也就是 out 又是data/Wikipedia-Cities.csv）
    # 否则下载dest文件
    if os.path.isfile(dest):
        print(f"{dest} found locally!")
    else:
        print(f"{dest} not found, downloading!")
        
        # 通过 urlopen 获得数据
        # 将 src（也就是url）读入名为'response'的变量
        # 从response读取，解码，得到真正的数据
        response = urlopen(src) 
        filedata = response.read().decode('utf-8')
        
        # os.path.split 意为分割dest（data/Wikipedia-Cities.csv）
        # path就是dest 倒数第一个文件 （Wikipedia-Cities.csv）
        path = list(os.path.split(dest)[:-1])
        
        
        # Create any missing directories in dest(ination) path
        # -- os.path.join is the reverse of split (as you saw above)
        # but it doesn't work with lists... so I had to google how 
        # to use the 'splat' operator! os.makedirs creates missing 
        # directories in a path automatically.
        if len(path) >= 1 and path[0] != '':
            os.makedirs(os.path.join(*path), exist_ok=True)
        
        with open(dest, 'w') as f:
            f.write(filedata)
            
        print(f"Data written to {dest}!")
    
   
    return dest
        

src = get_url(url, out)

data/Wikipedia-Cities.csv found locally!


<div class="alert alert-block alert-warning">
    <b>&#9888; Stop!</b> It really would be a good idea to put in the effort to make sense of how this function works. There is a lot going on here and understanding how this function works will help you to understand how to code. You should notice that we don't try to check if the data file contains any useful data! So if you download or create an empty file while testing, you won't necessarily get an error until you try to turn it into data afterwards!</div>

### Task 2.2: Parse the CSV File

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low</div>

Now we turn to the next task: parsing the file if it's a CSV. This implies that it *might* not be so that's something we should also consider!

In [23]:
# 需要解析该文件是否为 csv (避免影响后续工作）🍜


#  read_csv 和 csv.reader 基本上作用一样，即
# 使用csv模块读取文件，自动split分割逗号，形成列表数据
# 只是，read_csv读取文件后会保持原始数据的列名称

# src => url => websiteData （由上所得）

import csv

# 使用csv模块读取src文件
def read_csv(src):
    
    # 列表csvdata 中存在 列表csvr
    # 列表csvr 是f的csv格式
    # f 即 （'websiteData','r')
    csvdata = []
    with open(src, 'r') as f:
        csvr = csv.reader(f)
        
        # 'r' 在列表csvr
        # 那么列表csvdata 也会出现 'r'
        for r in csvr:
            csvdata.append(r)
    
    # Return list of lists
    return csvdata

read_csv(src)

[['City', 'Population', 'Latitude', 'Longitude'],
 ['Perth', '45770', '56.39583', '-3.43333'],
 ['Armagh', '14777', '54.3499', '-6.6546'],
 ['Dundee', '147268', '56.462', '-2.9707'],
 ['Colchester', '194706', '51.88861', '0.90361'],
 ['Salisbury', '40302', '51.07', '-1.79'],
 ['Portsmouth', '205056', '50.80583', '-1.08722'],
 ['Wakefield', '325837', '53.683', '-1.499'],
 ['Bradford', '522452', '53.792', '-1.754'],
 ['Lancaster', '138375', '54.047', '-2.801'],
 ['Bangor', '18808', '53.228', '-4.128']]

You should get:

```
[['City', 'Population', 'Latitude', 'Longitude'],
 ['Perth', '45770', '56.39583', '-3.43333'],
 ['Armagh', '14777', '54.3499', '-6.6546'],
 ['Dundee', '147268', '56.462', '-2.9707'],
 ['Colchester', '194706', '51.88861', '0.90361'],
 ['Salisbury', '40302', '51.07', '-1.79'],
 ['Portsmouth', '205056', '50.80583', '-1.08722'],
 ['Wakefield', '325837', '53.683', '-1.499'],
 ['Bradford', '522452', '53.792', '-1.754'],
 ['Lancaster', '138375', '54.047', '-2.801'],
 ['Bangor', '18808', '53.228', '-4.128']]
```

### Task 2.3: Convert the CSV into a DoL

<div class="alert alert-block alert-warning"><b>Difficulty level</b>: Medium.</div>

Now we can focus on converting the CSV data to a dictionary-of-lists! We're going to start with the *same* function name but expand what the function *does*. This kind of *iteration* is common in software development.

In [24]:
# 使用read_csv/ csv.reader读取文件，自动split分割逗号，形成列表数据
# 获取一行中的某一列数据，只能通过列表的索引，不方便

# 因此，这一步把csv data 转换为 dictionary-of-list 😊

def read_csv(src):
    
    csvdata = {} # 一个空的 dictionary-of-lists
    
    with open(src, 'r') as f:
        csvr = csv.reader(f)
        
        # 读入 column列 名称
        # 初始化 dictionary-of-lists
        csvcols = next(csvr) 
        for c in csvcols:
            csvdata[c] = []
        
        # Notice this code is still the same, 
        # we just used next(csvr) to get the 
        # header row first!
        for r in csvr: 
            # Although you can often assume that the order 
            # of the keys is the same, Python doesn't 
            # guarantee it; this way we will always make
            # the correct assignment.
            for idx, c in enumerate(csvcols):
                csvdata[c].append(r[idx])
    
    # 转换完成 返回 dictionary-of-lists
    return csvdata

read_csv(src)

{'City': ['Perth',
  'Armagh',
  'Dundee',
  'Colchester',
  'Salisbury',
  'Portsmouth',
  'Wakefield',
  'Bradford',
  'Lancaster',
  'Bangor'],
 'Population': ['45770',
  '14777',
  '147268',
  '194706',
  '40302',
  '205056',
  '325837',
  '522452',
  '138375',
  '18808'],
 'Latitude': ['56.39583',
  '54.3499',
  '56.462',
  '51.88861',
  '51.07',
  '50.80583',
  '53.683',
  '53.792',
  '54.047',
  '53.228'],
 'Longitude': ['-3.43333',
  '-6.6546',
  '-2.9707',
  '0.90361',
  '-1.79',
  '-1.08722',
  '-1.499',
  '-1.754',
  '-2.801',
  '-4.128']}

You should get something that starts:
```
{'City': ['Perth',
  'Armagh',
  'Dundee',
  'Colchester',
  'Salisbury',
  'Portsmouth',
  'Wakefield',
  'Bradford',
  'Lancaster',
  'Bangor'],
 'Population': ['45770',
```

### Task 2.4: Adding Docstring

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low</div>

We've assumed that the first row of our data set is always a _header_ (i.e. list of column names). If it's not then this code is going to have problems. A _robust_ function would allow us to specify column names, skip rows, etc. when we create the data structure, but let's not get caught up in that level of detail. Notice that I've also, for the first time:

1. Used the docstring support offered by Python. You'll be able to use `help(...)` and get back the docstring help!
2. Provided hints to Python about the expected input and output data types. This can help to ensure consistency and is also critical in testing / continuous integration when working with others on a codebase.

In [25]:
# csv file 转换+构建 DOL数据结构时
# 预测、识别数据第一行
# 如果第一行是列名称， 自动创建为 DOL形式的列名称🥧
# 如果第一行不是，则手动指定某一行

def read_csv(src:str) -> dict:
    """
    Converts a CSV file to a dictionary-of-lists (dol),
    using the first row to create column names.
    
    :param src: local csv file
    :returns: DOL
    """
    csvdata = {} # 一个空的 dictionary-of-lists
    
    with open(src, 'r') as f:
        csvr = csv.reader(f)
        
        # 读入 column列 名称
        # 初始化 dictionary-of-lists
        csvcols = next(csvr) 
        for c in csvcols:
            csvdata[c] = []
        
        # Notice this code is still the same, 
        # we just used next(csvr) to get the 
        # header row first!
        for r in csvr: 
            # Although you can often assume that the order 
            # of the keys is the same, Python doesn't 
            # guarantee it; this way we will always make
            # the correct assignment.
            for idx, c in enumerate(csvcols):
                csvdata[c].append(r[idx])
    
    # 转换完成 返回 dictionary of lists
    return csvdata

ds = read_csv(src)

In [27]:
help(read_csv)

Help on function read_csv in module __main__:

read_csv(src: str) -> dict
    Converts a CSV file to a dictionary-of-lists (dol),
    using the first row to create column names.
    
    :param src: local csv file
    :returns: DOL



In [28]:
print("Columns are: " + ", ".join(ds.keys()))
print(f"First two cities are: {ds['City'][:2]}")
print(f"First two populations are: {ds['Population'][:2]}")
print(f"First two latitudes are: {ds['Latitude'][:2]}")

Columns are: City, Population, Latitude, Longitude
First two cities are: ['Perth', 'Armagh']
First two populations are: ['45770', '14777']
First two latitudes are: ['56.39583', '54.3499']


The answer should look like:
```
Columns are: City, Population, Latitude, Longitude
First two cities are: ['Perth', 'Armagh']
First two populations are: ['45770', '14777']
First two latitudes are: ['56.39583', '54.3499']
```

### Task 2.5: Fixing Data Types

<div class="alert alert-block alert-warning"><b>Difficulty level</b>: Medium.</div>

If you look closely at the above, you'll see that *everything* is a string, including the latitudes, longitudes, and populations, which are clearly numeric data types. Here's a 'simple' way to specify a `dtype` list to hold the _data type_ for each column. I'm also going to introduce you the `zip` function here as it has many uses with geographic data (especially converting lat/long to points).

#### 2.5.1 Demonstrating Zip

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low</div>

In [29]:
# dtype 可以保持每一列的数据类型 🍍
# zip函数 经常用于地理数据 （比如，可以把经纬度转换为"点"）

# str字符串，int整数，float小数
cols  = ['City', 'Population', 'Latitude', 'Longitude'] # <- Column name
dtype = [str, int, float, float]                        # <- Column data type


# cols，dtype两个列表 压缩到同一个迭代器 zip
for col in zip(cols, dtype):
    colname = col[0]
    coltype = col[1]
    

    # - `>12` 意味着向右对其，空格不超过12字符
    print(f"Column {colname:>12} should be type: {coltype.__name__}")

Column         City should be type: str
Column   Population should be type: int
Column     Latitude should be type: float
Column    Longitude should be type: float


#### 2.5.2 A Function to Convert Data Types

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low, as I've provided a function.</div>

In [30]:
# 原始数据 转换为 适当的数据

# 下面是在讲转换的原理 φ(◎ロ◎;)φ

# type: 'column data' (cdata) -> 'column type' (ctype)

def to_type(cdata, ctype):
    # If a string
    if isinstance(cdata, str):
        try:
            if ctype==bool:
                return cdata==True
            else:
                return ctype(cdata)
        except TypeError:
            return cdata
    
    # Not a string (assume list)
    else: 
        fdata = []
        for c in cdata:
            try:
                if ctype==bool:
                    fdata.append( c=='True' )
                else:
                    fdata.append( ctype(c) )
            except:
                fdata.append( c )
        return fdata

In [31]:
# ds = read_csv(src) ，就是csv file 转换为 DOL 的结果
# 码10 给每一列数据分了类型
# ds2是根据 码10的分类，对ds数据每一列进行分类

# ds是数据['45770']  ds2只是类型[45770]

ds2 = {}
for col in zip(cols, dtype):
    colname = col[0]
    coltype = col[1]
    ds2[ colname ] = to_type( ds[colname], coltype )

print(ds2)    

{'City': ['Perth', 'Armagh', 'Dundee', 'Colchester', 'Salisbury', 'Portsmouth', 'Wakefield', 'Bradford', 'Lancaster', 'Bangor'], 'Population': [45770, 14777, 147268, 194706, 40302, 205056, 325837, 522452, 138375, 18808], 'Latitude': [56.39583, 54.3499, 56.462, 51.88861, 51.07, 50.80583, 53.683, 53.792, 54.047, 53.228], 'Longitude': [-3.43333, -6.6546, -2.9707, 0.90361, -1.79, -1.08722, -1.499, -1.754, -2.801, -4.128]}


Compare the output here to the output from `ds` up above:

In [32]:
print("Columns are: " + ", ".join(ds2.keys()))
print(f"First two cities are: {ds2['City'][:2]}")
print(f"First two populations are: {ds2['Population'][:2]}")
print(f"First two latitudes are: {ds2['Latitude'][:2]}")

Columns are: City, Population, Latitude, Longitude
First two cities are: ['Perth', 'Armagh']
First two populations are: [45770, 14777]
First two latitudes are: [56.39583, 54.3499]


You should get the followg:
```
Columns are: City, Population, Latitude, Longitude
First two cities are: ['Perth', 'Armagh']
First two populations are: [45770, 14777]
First two latitudes are: [56.39583, 54.3499]
```

### Task 2.6: Checking Basic Functionality

<div class="alert alert-block alert-warning"><b>Difficulty level</b>: Medium</div>

Now that we've got our data structure all set up correctly (appropriate names, data types, etc.) let's see if it works by testing out some of our previous operations:

In [33]:
# 利用 numpy函数查找位于 东西南北最极端的城市 🌏🌹(｡･∀･)ﾉﾞ

# 公式： {ds2['City'][np.where(ds2['Longitude']==np.min(ds2['Longitude']))[0][0]]}
# ds2：DOL形式的数据
# min'Longitude'最西端  max'Longitude'最东端
# min'Latitude'最南端  max'Latitude'最北端


import numpy as np # We'll need this to apply functions to lists easily

print(f"Average population is {np.mean(ds2['Population']):,.2f}")
print(f"Westernmost city is {ds2['City'][np.where(ds2['Longitude']==np.min(ds2['Longitude']))[0][0]]}")
print(f"Northernmost city is {ds2['City'][np.where(ds2['Latitude']==np.max(ds2['Latitude']))[0][0]]}")
print(f"Southernmost city is {ds2['City'][np.where(ds2['Latitude']==np.min(ds2['Latitude']))[0][0]]}")

Average population is 165,335.10
Westernmost city is Armagh
Northernmost city is Dundee
Southernmost city is Portsmouth


You should get the following:

```
Average population is 165,335.10
Westernmost city is Armagh
Northernmost city is Dundee
Southernmost city is Portsmouth
```

There are a few things to understand here:

1. Where we want to find something else in the data *based on that value* then things get a little more complex: we use `np.min` to find the smallest value in the data, but we don't know *where* in the list that value actually *was* so we use `np.where` to find out which indexes match the minimum value. In this data set it's easy because there's one, and only one value that matches. But you'd need to do some clever thinking about how to handle ties.
2. `np.where` returns a complex data structure (list-of-lists, essentially) so we need to pull the value we need out of that data in order to actually find the list index we need and look up the `City` name associated with, for example, the minium value in the data. That bit (`[0][0]`) is a bit clunky, but right now we're not too worried about it.

**Notice** that we do *all* of this without using a `for` loop or variables to keep track of what we've found... You *could* also use a `for` loop to answer each of these questions (see the example below), but hopefully you see what the way we've used above is more *elegant* (it's also faster):

In [34]:
# 以下是使用for循环查找信息
# 但码21的方式更智慧

min_long = 180
min_idx  = -1

for l in ds2['Longitude']:
    if l < min_long: min_long = l
print(f"Minimum longitude is {min_long}")

for idx, l2 in enumerate(ds2['Longitude']):
    if l2==min_long:
        min_idx = idx
        break

print(f"Westernmost city is {ds2['City'][min_idx]}")

Minimum longitude is -6.6546
Westernmost city is Armagh


## Task 3. Was it Worth It?

<div class="alert alert-block alert-success"><b>Difficulty level</b>: Low</div>

At this point it's worth asking: was all this *worth* it? Let's see! 

The best way to test is to use a *different* data set and see if we've solved the 'hard-coding' problem.

In [35]:
# 使用不同数据集 检验代码


url = "https://raw.githubusercontent.com/jreades/fsds/master/data/src/Wikipedia-Cities.csv"
out = os.path.join('data','Wikipedia-Cities-full.csv')

cols  = ['City', 'Population', 'Latitude', 'Longitude']
dtype = [str, int, float, float]

untyped_dol = read_csv(get_url(url, out))

typed_dol = {}
for col in zip(cols, dtype):
    colname = col[0]
    coltype = col[1]
    typed_dol[ colname ] = to_type(untyped_dol[colname], coltype)

data/Wikipedia-Cities-full.csv found locally!


In [36]:
print(f"Average population is {np.mean(typed_dol['Population']):,.2f}")
print(f"Westernmost city is {typed_dol['City'][np.where(typed_dol['Longitude']==np.min(typed_dol['Longitude']))[0][0]]}")
print(f"Northernmost city is {typed_dol['City'][np.where(typed_dol['Latitude']==np.max(typed_dol['Latitude']))[0][0]]}")
print(f"Southernmost city is {typed_dol['City'][np.where(typed_dol['Latitude']==np.min(typed_dol['Latitude']))[0][0]]}")

Average population is 202,283.36
Westernmost city is Derry
Northernmost city is Inverness, Inerness, Inbhir Nis
Southernmost city is Truro


You should get:

```
Average population is 202,283.36
Westernmost city is Derry
Northernmost city is Inverness, Inerness, Inbhir Nis
Southernmost city is Truro
```

So we used all the same code as for the subset of the data but changed *nothing*. And this is even though the column order changed (print out the first row of each file if you don't believe me) *and* the number of columns changed *and* our city column now contains commas! So what this has given us is a much more flexible way not only to *access* the data, but also to *work* with it!

## Task 4. More Functions!

<div class="alert alert-block alert-warning"><b>Difficulty level</b>: Medium</div>

Here is the skeleton of a function to replace the `np.where(column==np.[min|max|...](column))[0][0]` code. There are a few ways to do this: 

1. You could use if/else/elif and do different things based on testing against the specified string
2. You could try to find a function in `numpy` that matches the specified string
3. You could try to `eval` the code, but I really wouldn't recommend this for security reasons

I have gone with a combination of 1 and 2, but you will need to really read the code to understand how it works. I've left the docstring for you to complete. This isn't the best function since it makes some assumptions about the types of data that it might be passed to the function: this is where *Object-Oriented Programming* could come to the rescue! If we had different column *types* (e.g. String, Float, Int) then we could have different *versions* of `find_val` that performed the same *function* (find a value) but did this completely differently depending on the data. This is what *methods* do!

In [37]:
# 用更简便方式 计算 挑选 数据 
# 使用 numpy 的功能 find_val (意为 find a value）


import numpy as np

def find_val(col:list, val:str):
    """
    :param col: a list of numeric values
    :param val: what kind of value to search for (in the sense of min, max, median, etc.)
    :returns: the result of the search (e.g. the minimum value in the list as located by the numpy function)
    """
    if val in dir(np) and callable(getattr(np, val)):
        func = getattr(np, val) # <--- What does this do???
        if val in ['min','max']:
            return np.where(col==func(col))[0][0]
        else:
            return func(col)
    else:
        return np.nan
    
print(find_val(typed_dol['Latitude'], 'min'))
print(find_val(typed_dol['Latitude'], 'median'))

65
52.801835


In [38]:
print(f"Average population is {find_val(typed_dol['Population'],'mean'):,.2f}")
print(f"Westernmost city is {typed_dol['City'][find_val(typed_dol['Longitude'],'min')]}")
print(f"Northernmost city is {typed_dol['City'][find_val(typed_dol['Latitude'],'max')]}")
print(f"Southernmost city is {typed_dol['City'][find_val(typed_dol['Latitude'],'min')]}")

Average population is 202,283.36
Westernmost city is Derry
Northernmost city is Inverness, Inerness, Inbhir Nis
Southernmost city is Truro


So we have streaminlined the code still further and implemented a fairly generic 'helper' function that uses `numpy` to perform calculations on a column of data (assuming it's numeric). We could, of course, extend this further, to handle strings and other data types, but we're going to see a *better* way to do all of this *next* week.

## Task 5. Creating a Package from Functions

<div class="alert alert-block alert-danger"><b>Difficulty level</b>: Hard.</div>

Below is code to create a package called `dtools` (i.e. data tools) by converting the notebook into a Python script file called `__init__.py` that sits in the `dtools` directory. This is the first step to creating a package from code that is *already* working in a Notebook.

### Task 5.1 Create a Directory

When creating your own package, everything goes into a directory whose name is the name of the package. In other words, if you wanted to create a package called `my_stuff` then you'd need to *first* create a directory called `my_staff` in the *current working directory* (i.e. wherever you are keeping your Notbooks).

We can create the directory using `mkdir` (the `!` means 'run this [Linux] command'):

In [39]:
# 创建 名为dtools的功能包，将其放在自己的目录 fsds_J里 🦁

!mkdir -p 'dtools'

### Task 5.2 Create \_\_init\_\_.py

More complex packages will have lots of stuff going on inside their 'root' directory, but we're keeping it simple and only need to create and fill in *one* file inside the `dtools` directory: `__init__.py`. This is a convention.

We can create this file two ways: 

1. By creating an empty file with that name in `dtools` (e.g. `!touch dtools/__init__.py` would work!)
2. By converting *this* entire notebook to a Python script and then removing all the stuff that *is not* a function that we need to keep.

The 'hybrid' way, which I'm going to suggest you use so you get some more experience, would be to convert this notebook to a Python script file, open it, and then copy the functions out into `__init__.py`. 

In [40]:
# 在dtools目录中创建并填充一个文件:_init_.py
# _init_.py 包含了下面四行的功能 (url csv type val)

# _init_.py 在一定程度上简化了数据读取、选择、提取？？


!touch dtools/__init__.py
# Comment out so we don't automatically re-run this code every time
!jupyter nbconvert --ClearOutputPreprocessor.enabled=True \
    --to python --output=dtools/notebook.py \
    Practical-04-Objects-Answers.ipynb

[NbConvertApp] Converting notebook Practical-04-Objects-Answers.ipynb to python
[NbConvertApp] Writing 40040 bytes to dtools/notebook.py


### Task 5.3 Extract Code to Init

You now need to open `notebook.py` and find+copy the following functions into `__init__.py`:

1. `get_url`
2. `read_csv` 
3. `to_type` 
4. `find_val`

And don't forget to find all the `import` statements (including `from x import y`) and copy those as well!

You should then be able to run the code below and can always compare it to my version [on GitHub](https://github.com/jreades/fsds/blob/master/practicals/dtools/__init__.py).

### Task 5.6 Test

The next two lines of code allow you to repeatedly edit an imported package without having to restart the entire Python notebook. So whenever Jupyter sees a change to `dtools/__init__.py` it will reload the package and update the code without you having to do anything.

In [43]:
# 以下支持重复编辑功能包
# dtools/_init_.py 有改动时，Jupyter自动加载

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


#### 5.6.1 Import

And now we should be able to import the package and start using the functions that we defined...

In [54]:
# 加载 dtools 功能包，及其 read csv功能

import dtools
help(dtools.read_csv)

Help on function read_csv in module dtools:

read_csv(src: str) -> dict
    Converts a CSV file to a dictionary-of-lists (dol),
    using the first row to create column names.
    
    :param src: a local CSV file
    :returns: a dictionary-of-lists



#### 5.6.2 Use Read_CSV

In [60]:
url = 'https://github.com/jreades/fsds/raw/master/data/2019-sample-crime.csv'
out = os.path.join('data','crime-sample.csv')

ds = dtools.read_csv(dtools.get_url(url, out))

Found data/crime-sample.csv locally!


In [56]:
print(f"ds has {len(ds.keys())} columns, these are: " + ", ".join(ds.keys()))
print(f"There are {len(ds['ID'])} rows of data")

ds has 11 columns, these are: ID, Case Number, Date, Primary Type, Description, Location Description, Arrest, Domestic, Year, Latitude, Longitude
There are 100 rows of data


#### 5.6.3 Use To_Type

In [62]:
cols  = ['Latitude', 'Longitude'] 
dtype = [float, float]

typed_ds = {}
for col in zip(cols, dtype): # <- This only copies these two columns to typed_ds
    colname = col[0]
    coltype = col[1]
    typed_ds[ colname ] = dtools.to_type(ds[colname], coltype)

#### 5.6.4 Use Find_Val

In [63]:
idx = find_val(typed_ds['Latitude'], 'min')

In [59]:
print(ds['Case Number'][idx])
print(ds['Description'][idx])

JC227392
DOMESTIC BATTERY SIMPLE


## Task 6. Brain Teaser

<div class="alert alert-block alert-danger"><b>Difficulty level</b>: &#129327;.</div>

And now for something completely different!

We want to create a set of 'ideal shapes' with methods allowing us to derive various properties of that shape:

- Diameter: which we'll define as the longest line that can be drawn across the inside of the shape.
- Volume: the total volume of the shape.
- Surface Area: the total outside area of the shape.

We will create all of these shape classes in the notebook so that we know they work and then will move them to an external package file so that they can be imported and re-used easily in other notebooks.

We're also going to make use of a few features of Python:

- You can access the class name of an instance using: `self.__class__.__name__`. And here's one key point: `self` refers to the instance, not to the class... we'll see why this matters.
- You can raise your own exceptions easily if you don't want to implement a particular method yet.
- You can have an 'abstract' base class that does nothing except provide a template for the 'real' classes so that they can be used interchangeably.


### Task 6.1 Abstract Base Class

This class appears to do very little, but there are two things to notice:

1. It provides a constructor (`__init__`) that sets the `shape_type` to the name of the class automatically (so a `square` object has `shape_type='Square'`) and it stores the critical dimension of the shape in `self.dim`.
2. It provides methods (which only raise exceptions) that will allow one shape to be used in the place of any other shape that inherits from `shape`.

In [69]:
# 使用 _init_ 绘制图形 🎂🍮
# 给予 _init_ 一些数学公式的功能

from math import pi

# Base class shape
class shape(object): # Inherit from base class 
    def __init__(self, dimension:float=None):
        self.shape_type = self.__class__.__name__.capitalize()
        self.dim = dimension
        return
    
    def diameter(self):
        raise Exception("Unimplmented method error.")
    
    def volume(self):
        raise Exception("Unimplmented method error.")
    
    def surface(self):
        raise Exception("Unimplmented method error.")
        
    def type(self):
        return(self.shape_type)

### Task 6.2 Cube

Implements a cube:

1. The diameter of the cube is given by the Pythagorean formula for the length of the hypotenuse in 3D between opposing corners: $\sqrt{d^{2} + d^{2} + d^{2}}$ which we can reduce to $\sqrt{3 d^{2}}$.
2. A cube's volume is given by $d^{3}$.
3. A cube's surface area will be the sum of its six faces: $6d^{2}$.

In [70]:
# 绘制立方体
# 基于上面三条公式，根据半径dim 可以计算cube的 直径diameter 体积volume 表面积surface

# Cube class
class cube(shape): # Inherit from shape 
    def __init__(self, dim:float):
        super().__init__(dim)
        return
    
    def diameter(self):
        return (3 * self.dim**2)**(1/2)
    
    def volume(self):
        return self.dim**3
    
    def surface(self):
        return 6*(self.dim**2)

### Task 6.3 Sphere

Implements a sphere:

1. The diameter is twice the critical dimension (radius): $2d$. 
2. The volume is $\frac{4}{3} \pi r^{3}$.
3. The surface area will be $4 \pi r^{2}$.

If we were writing something more general, we'd probably have spheres as a special case of an ellipsoid!

In [71]:
# 绘制球体
# 基于上面三条公式，根据半径dim 可以计算sphere的 直径diameter 体积volume 表面积surface

# Sphere
class sphere(shape): # Inherit from shape 
    def __init__(self, dim:float):
        super().__init__(dim)
        return
    
    def diameter(self):
        return 2 * self.dim
    
    def volume(self):
        return (4/3) * pi * (self.dim**3)
    
    def surface(self):
        return 4 * pi * (self.dim**2)

### Task 6.4 Regular Pyramid

We're taking this to be a regular pyramid where all sides are equal: 

1. The diameter is a line drawn across the base between opposing corners of the base so it's just $\sqrt{d^{2} + d^{2}}$.
2. The volume is given by $V = b * h / 3$ (where $b$ is the area of the base, which in this case becomes $d^{2} * h/3$).
3. The surface area will be the base + 4 equilateral triangles: $d^{2} + 4 (d^{2}\sqrt{3}/4)$ which we can reduce to $d^{2} + d^{2}\sqrt{3}$

But this requires a _height_ method that is specific to pyramids:

4. The height is taken from the centre of the pyramid (which will be half the length of the hypotenuse for two edges): $l = \sqrt{d{^2} + d^{2}}$ and the long side ($d$ again) which gives us $\sqrt{l/2 + d^{2}}$.

Note that this has a class variable called `has_mummies` since Egyptian regular pyramids are plagued by them! 

In [72]:
# regular pyramid 正角锥体
# 公式中的 l 就是 直径diameter


# Pyramid class
class pyramid(shape): # Inherit from shape
    
    has_mummies = True # This is for *all* regular pyramids
    
    def __init__(self, dim:float):
        super().__init__(dim)
        self.shape_type = 'Regular Pyramid'
        return
    
    def diameter(self):
        return (self.dim**2 + self.dim**2)**(1/2)
    
    def height(self):
        return (self.diameter()/2 + self.dim**2)**(1/2)
    
    def volume(self):
        return self.dim**2 * self.height() / 3
    
    def surface(self):
        return self.dim**2 + self.dim**2 * 3**(1/2)

### Task 6.5 Triangular Pyramid

We want triangular pyramid to inherit from regular pyramid, and all sides are equal so it's an _equilateral_ triangular pyramid. However, this is kind of a judgement call since there's very little shared between the two types of pyramid and it's arguable whether this one is actually simpler and should therefore be the parent class...

Anyway, the calculations are:

1. The diameter (longest line through the shape) will just be the edge: $d$.
2. The volume $V = b * h / 3$ where $b$ is the area of an equilateral triangle.
3. The surface area will be $4b$ where $b$ is the area of an equilateral triangle.

So we now need two new formulas:

5. The height of the pyramid using ([Pythagoras again](https://www.youtube.com/watch?v=ivF3ndmkMsE)): $h = \sqrt{6}d/3$.
6. The area of an equilateral triangle: $\frac{\sqrt{3}}{4} d^{2}$

Triangular pyramids do *not* have a problem with mummies.

In [73]:
# Triangular pyramid 三棱锥
# 根号6 ： 6**(1/2)


# Triangular Pyramid class
class t_pyramid(shape): # Inherit from shape
    
    has_mummies = False # This is for *all* regular pyramids
    
    def __init__(self, dim:float):
        super().__init__(dim)
        self.shape_type = 'Triangular Pyramid'
        return
    
    def diameter(self):
        return self.dim
    
    def height(self):
        return 6**(1/2)/3 * self.dim
    
    def base(self):
        return 3**(1/2)/4 * self.dim**2
       
    def volume(self):
        return (1/3) * self.base() * self.height()
    
    def surface(self):
        return 4 * self.base()

### Task 6.6 Testing Your Classes

If you've implemented everything correctly then the following code should run.

In [82]:
# 检测上面绘制的 4 个图形
# Cube, Sphere, Regular Pyramid, Triangular Pyramid


s = sphere(10)
print(s.type())
print(f"\tVolume is: {s.volume():5.2f}")
print(f"\tDiameter is: {s.diameter():5.2f}")
print(f"\tSurface Area is: {s.surface():5.2f}")
print("")

c = cube(10)
print(c.type())
print(f"\tVolume is: {c.volume():5.2f}")
print(f"\tDiameter is: {c.diameter():5.2f}")
print(f"\tSurface Area is: {c.surface():5.2f}")
print("")

p = pyramid(10)
print(p.type())
print(f"\tVolume is: {p.volume():5.2f}")
print(f"\tDiameter is: {p.diameter():5.2f}")
print(f"\tSurface Area is: {p.surface():5.2f}")
print(f"\tHeight is: {p.height():5.2f}")
if p.has_mummies is True:
    print("\tMummies? Aaaaaaaaagh!")
else:
    print("\tPhew, no mummies!")
print("")

p2 = t_pyramid(10)
print(p2.type())
print(f"\tVolume is: {p2.volume():5.2f}")
print(f"\tDiameter is: {p2.diameter():5.2f}")
print(f"\tSurface Area is: {p2.surface():5.2f}")
print(f"\tHeight is: {p2.height():5.2f}")
if p2.has_mummies is True:
    print("\tMummies? Aaaaaaaaagh!")
else:
    print("\tPhew, no mummies!")
print("")

# Useful demonstration of how to find out if a method or attribute is
# associated with a particular object
if hasattr(p2,'base_area'):
    print(f"Shape of type '{p2.type()}' has attribute or method 'base_area'")
else:
    print(f"Shape of type '{p2.type()}' does *not* have attribute or method 'base_area'")
print("")

Sphere
	Volume is: 4188.79
	Diameter is: 20.00
	Surface Area is: 1256.64

Cube
	Volume is: 1000.00
	Diameter is: 17.32
	Surface Area is: 600.00

Regular Pyramid
	Volume is: 344.92
	Diameter is: 14.14
	Surface Area is: 273.21
	Height is: 10.35
	Mummies? Aaaaaaaaagh!

Triangular Pyramid
	Volume is: 117.85
	Diameter is: 10.00
	Surface Area is: 173.21
	Height is:  8.16
	Phew, no mummies!

Shape of type 'Triangular Pyramid' does *not* have attribute or method 'base_area'



I get the following output:

```
Sphere
	Volume is: 4188.79
	Diameter is: 20.00
	Surface Area is: 1256.64

Cube
	Volume is: 1000.00
	Diameter is: 17.32
	Surface Area is: 600.00

Regular Pyramid
	Volume is: 344.92
	Diameter is: 14.14
	Surface Area is: 273.21
	Height is: 10.35
	Mummies? Aaaaaaaaagh!

Triangular Pyramid
	Volume is: 117.85
	Diameter is: 10.00
	Surface Area is: 173.21
	Height is:  8.16
	Phew, no mummies!

Shape of type 'Triangular Pyramid' does *not* have attribute or method 'base_area'
```

### Task 6.7 Packaging It Up

Wait, you're *still* working on this practical and haven't thrown up your hands in disgust yet? OK, in that case you can have *one* more thing to do: turn the whole shapes class hierarchy into a package that can be loaded via an `import` statement. 

#### 6.7.1 Cell Magic

This code allows Jupyter to reload external libraries if they are edited after you import them. When you are working on your own packages this is rather useful since you tend to make a *lot* of mistakes when packaging code up this way and it's handy not to have to restart the entire notebook every time you fix a typo or change a function.

In [77]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


#### 6.7.2 Import Shapes

You can call your package whatever you like, but then it *has* to match what you `import` below. So remember that with `dtools` we had `dtools/__init__.py`? You'll need to do the same here so that you can import the package.

In [ ]:
# 首先，需要在 _init_.py 文件里写入shapes



#### 6.7.3 Adding Documentation

In an ideal world, this would also be the time to properly document your classes and methods. Here as some examples that you could add to the `__init__.py` package file.

Underneath the line `class shape(object):`, add:
```
    """Abstract base class for all ideal shape classes.

    Keyword arguments:
    dimension -- the principle dimension of the shape (default None)
    """
```

Underneath the line `def type(self):`, add:
```
        """
        Returns the formatted name of the shape type. 
        
        This is set automatically, but can be overwritten by setting the attribute shape_type.
        
        :returns: the name of the class, so shapes.cube is a `Cube` shape type
        :rtype: str
        """
```

In [ ]:
import shapes # <-- Change this if you didn't call your package `shapes`!
help(shapes.shape)
help(shapes.shape.type)